### ISSUE TITLE
Decide on License

### ISSUE THREAD

**Issue by DamonOehlman** [pull-stream/pull-ws#9]
When I wrote my implementation I just went with the default npm was suggesting at the time.  I see you went with MIT which I think is also a good choice.  I'm happy with either, but I'm guessing we should go with one of the other and update references around the place to suit.

**Comment by dominictarr** [comment]
I don't really care, I just use MIT because that seems like the most popular (and have it in my [package initialization scripts](https://github.com/dominictarr/gen)). Sometimes people send me pull requests for another license (like, i think apache2 is more specific so it gives lawyers clarity) and I just add it.
